module.exports = {
  verbose: true,
  globals: {
    'ts-jest': {
      isolatedModules: true,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/jest.js'],
  roots: ['./', '../../shared/common/src/', '../../shared/client-common/src/'],
  testEnvironment: 'jest-environment-jsdom',
  testEnvironmentOptions: {
    customExportConditions: ['node', 'node-addons'],
  },
  coverageReporters: ['lcov'],
  coverageDirectory: './coverage',
  collectCoverageFrom: [
    'src/**/*.ts',
    'src/**/*.tsx',
    '../../shared/common/src/**/*.ts',
    '../../shared/common/src/**/*.tsx',
    // exclude files from coverage
    '!src/**/index.ts',
    '!src/**/index.tsx',
    '!src/**/App.tsx',
    '!src/**/react-app-env.d.ts',
    '!src/**/reportWebVitals.ts',
    '!src/**/setupTests.ts',
    '!../../shared/common/src/**/index.ts',
    '!../../shared/common/src/**/index.tsx',
  ],
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
  moduleDirectories: ['node_modules'],
  moduleNameMapper: {
    '^@assets$': '<rootDir>/../../shared/common/src/assets',
    '^@assets/(.*)$': '<rootDir>/../../shared/common/src/assets/$1',
    '^@components$': '<rootDir>/../../shared/common/src/components',
    '^@components/(.*)$': '<rootDir>/../../shared/common/src/components/$1',
    '^@data$': '<rootDir>/../../docs',
    '^@data/(.*)$': '<rootDir>/../../docs/$1',
    '^@providers$': '<rootDir>/../../shared/client-common/src/providers',
    '^@providers/(.*)$':
      '<rootDir>/../../shared/client-common/src/providers/$1',
    '^@localization$': '<rootDir>/../../shared/common/src/localization',
    '^@localization/(.*)$': '<rootDir>/../../shared/common/src/localization/$1',
    '^@routes$': '<rootDir>/../../shared/client-common/src/routes',
    '^@routes/(.*)$': '<rootDir>/../../shared/client-common/src/routes/$1',
    '^@screens$': '<rootDir>/../../shared/client-common/src/screens',
    '^@screens/(.*)$': '<rootDir>/../../shared/client-common/src/screens/$1',
    '^@uiStore$': '<rootDir>/../../shared/client-common/src/store/ui',
    '^@uiStore/(.*)$': '<rootDir>/../../shared/client-common/src/store/ui/$1',
    '^@appStore$': '<rootDir>/../../shared/client-common/src/store/app',
    '^@appStore/(.*)$': '<rootDir>/../../shared/client-common/src/store/app/$1',
    '^@services$': '<rootDir>/../../shared/client-common/src/services',
    '^@services/(.*)$': '<rootDir>/../../shared/client-common/src/services/$1',
    '^@testUtils$': '<rootDir>/../../shared/common/src/testUtils',
    '^@testUtils/(.*)$': '<rootDir>/../../shared/common/src/testUtils/$1',
  },
  transform: {
    '^.+.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$':
      'jest-transform-stub',
    '^.+\\.(js|jsx|ts|tsx)$': 'ts-jest',
  },
  // coverageThreshold: {
  //   global: {
  //     branches: 80,
  //     functions: 80,
  //     lines: 80,
  //     statements: -10,
  //   },
  // },
};
