name: Server CI

on:
  push:
    branches:
      - development
    paths:
      - 'apps/server/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/ci-server.yml'
  pull_request:
    branches:
      - development
    paths:
      - 'apps/server/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/ci-server.yml'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  server-ci:
    name: Test and Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Tests
        run: cargo test
        working-directory: apps/server

      - name: Build Server
        run: cargo build
        working-directory: apps/server
