name: Server CI

on:
  push:
    paths:
      - 'server/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/ci-server.yml'
  pull_request:
    paths:
      - 'server/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/ci-server.yml'

jobs:
  test:
    name: Test Rust Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Tests
        run: cargo test
        working-directory: server

  build:
    name: Build Rust Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build Server
        run: cargo build
        working-directory: server
